build-job:
  stage: build
  image: ubuntu:22.04
  script:
    - apt-get update
    - apt-get install -y git cmake g++ freeglut3-dev qt6-base-dev 
    - mkdir -p build
    - cd build
    - cmake ..
    - cmake --build .

build-win64:
  tags:
    - "windows"
  before_script:
    - choco install -y cmake python
    - $env:Path += ';C:\Program Files\CMake\bin'
  stage: build
  script:
    - mkdir build 
    - cd build
    - cmake ..
    - cmake --build .
